apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: goldpinger
  namespace: default
spec:
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: goldpinger
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: goldpinger  
  podSelector:
    matchLabels:
      app: goldpinger
  policyTypes:
  - Egress
  - Ingress
